### ISSUE TITLE
☂️ Website for release

### ISSUE THREAD

**Issue by sebmck** [romefrontend/rome#496]
This issue lists improvements that need to be done to the existing website before we release:

- [X] <strike>Fix dark logo not being used on page load. (You need to flip the toggle twice to correct it)</strike> Fixed by @EduardoLopes in #497
- [X] <strike>Remove star count from homepage</strike> Fixed by @sreetamdas  in #498
- [X] <strike>Update tagline "Rome is an experimental JavaScript toolchain" to "Rome is a JavaScript toolchain"</strike> Fixed by @sreetamdas  in #498
- [X] <strike>Update tagline "A compiler, linter, formatter, bundler, testing framework and more" to "Linting, bundling, compiling, testing, and more"</strike> Fixed by @sreetamdas  in #498
- [X] <strike>Remove experimental warning banner</strike> Fixed by @sreetamdas  in #498
- [x] <strike>Remove Facebook open source footer and banner</strike>
- [x] <strike>Remove the selling point feature titles</strike>
- [x] <strike>Move all separate documentation pages into the homepage</strike>
- [ ] Extend homepage documentation to completely cover installation, what Rome supports, project setup, linting, and editor integration
- [x] <strike>Dark mode</strike>
- [x] <strike>Drop tocbot and add a custom script that generates the TOC</strike>
- [x] <strike>Fix conflict of heading with the same id (Getting started and Contributing - > Getting Start)</strike>
- [x] <strike>Add footer or a section with links for twitter,  discord server, open collective and etc</strike>
- [x] Support for screen-readers

I think we should invoke the clean and simple vibe from successful open source projects of old. Notably [CoffeeScript](http://coffeescript.org/), [Undercore](https://underscorejs.org/), and [Backbone](https://backbonejs.org/) (Basically any Jeremy Ashkenas project).

We should have a single page website that covers 90% of the documentation someone needs. It can be long. It should load fast. We should have a table of contents on the side to allow for quick jumping with excessive anchors to allow deep linking. It should be readable and understandable from someone reading top to bottom. We can have dedicated subpages for niche or advanced topics.

We don't need to prove ourselves to anyone. We don't need flashy bullet points or a comparison with existing tools right in your face when you go to the landing page. The website should be aimed at serving the users rather than serving as something flashy for adoption. Much less startupy.

It would be nice for us to migrate away from something complicated like [Docusaurus](https://docusaurus.io/) that we use to something like [Eleventy](https://www.11ty.dev/) that better serves the fast single-page content focused website that we want.

**Comment by EduardoLopes** [comment]
Once i wake up, i'll take care of the tasks that can already be applied to the current website. Then, i'll check out Eleventy!

**Comment by sreetamdas** [comment]
@sebmck shouldn't the README also be updated to remove the experimental warning and other things to keep in sync with the website?

**Comment by sebmck** [comment]
@sreetamdas Yeah it should.

**Comment by EduardoLopes** [comment]
Just pushed a branch for the new website: EduardoLopes/new-website

It setup eleventy with CSS and JS minification, syntax highlighting and automatic table of content using [Tocbot](https://tscanlin.github.io/tocbot).

I've added purecss as well, i think it's cool because we don't need to write much css to deal with responsive grids and stuff. And we can use only the parts we need (the base and grids). If it's overkill anyways, it's ok to remove it!

There's no design at all, i was just making things run! I care a lot about the design of the site, since i made the logo. I didn't make a doc to describe visual identity, so if you're working on the website, make sure to follow the design of the old website. I can tweak latter, if i feel like.

instructions on the README.md!

**Comment by EduardoLopes** [comment]
Thanks to @matvp91 we got a lot done already.

I've add some more tasks and created a pull request for review #507

**Comment by MareikeTaeubner** [comment]
What points are still in need for documentation? I kind of lost the overview ^^"

**Comment by matvp91** [comment]
@MareikeTaeubner sorry, we're mixing both the "old" Docusaurus site and the "new" Eleventy site.

Let's clean this up :)

**Comment by lishine** [comment]
Your website is down

**Comment by KidyasoVasiliy** [comment]
@sebmck  please, change description on repo
now is https://romejs.dev address is indicated there

thanks

**Comment by sebmck** [comment]
New website issues that are unowned/unassigned if anyone is interested:

- #730 Add blog to website
- #731 Comprehensive lint documentation for release
- #719 Mobile website homepage hero is squished 
- #720 Unicode characters are rendered as emoji on mobile website homepage preview

**Comment by ematipico** [comment]
@sebmck I think we can close this one, the website is finally live :)

**Comment by sebmck** [comment]
🎉
